---
# gnome variables

gsettings:
  theme:
    key: /org/gnome/desktop/interface/icon-theme
    value: Faenza-Darker
  clock-date:
    key: /org/gnome/desktop/interface/clock-show-date
    value: true
  mouse-modifier:
    key: /org/gnome/desktop/wm/preferences/mouse-button-modifier
    value: '<alt>'
  show-menubar:
    key: /org/gnome/Terminal/Legacy/Settings/default-show-menubar
    value: false
  enable-location:
    key: /org/gnome/system/location/enabled
    value: true
  max-location-accuracy:
    key: /org/gnome/system/location/max-accuracy-level
    value: street
  focus-mode:
    key: /org/gnome/desktop/wm/preferences/focus-mode
    value: sloppy
  enabled-extensions:
    key: /org/gnome/shell/enabled-extensions
    value: '["alternate-tab@gnome-shell-extensions.gcampax.github.com", "user-theme@gnome-shell-extensions.gcampax.github.com"]'
  favorite-apps:
    key: /org/gnome/shell/favorite-apps
    value: '["google-chrome.desktop", "firefox.desktop", "org.gnome.Nautilus.desktop", "org.gnome.Terminal.desktop"]'
  xkb-options:
    key: /org/gnome/desktop/input-sources/xkb-options
    value: '["caps:swapescape","terminate:ctrl_alt_bksp","altwin:swap_alt_win"]'
  disable-ambient-light:
    key: /org/gnome/settings-daemon/plugins/power/ambient-enabled
    value: false
  terminal-disable-menubar:
    key: /org/gnome/Terminal/Legacy/Settings/default-show-menubar
    value: false
  terminal-default-theme:
    key: /org/gnome/Terminal/Legacy/Settings/theme-variant
    value: 'dark'
  terminal-mnemonics:
    key: /org/gnome/Terminal/Legacy/Settings/mnemonics-enabled
    value: true
  disable-animantions:
    key: /org/gnome/desktop/interface/enable-animations
    value: false
  show-battery-percentage:
    key: /org/gnome/desktop/interface/show-battery-percentage
    value: true
  show-cursor:
    key: /org/gnome/settings-daemon/peripherals/mouse/locate-pointer
    value: true
  tap-to-click:
    key: /org/gnome/desktop/peripherals/touchpad/tap-to-click
    value: true
